version: "3.7"

services:
  nginx:
    image: nginx:latest
    networks:
      - ingress-nginx
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.ingress == yes
    healthcheck:
      test: ["CMD", "curl", "-f", "${wan}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ingress-nginx:
    external: true