version: "3.7"

services:
  node:
    image: consul:latest
    command: "agent -server -join=node -bootstrap-expect 3 -bind $(ip a | grep $(docker network ls -q -f 'name=ingress-nginx') | grep "scope" | grep -Po '(?<=inet )[\d.]+')"
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    networks: 
      - ingress-nginx

networks:
  ingress-nginx:
    external: true